config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root "static_pages#home"

  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'

  get '/guides' => 'guides#guides'
  resources :guides


end

app/models/guide.rb
class Guide < ActiveRecord::Base

  validates :guide_name, presence: true, length: { maximum: 50 }
  validates :address, presence: true, length: { maximum: 50 }
  validates :city, presence: true, length: { maximum: 17 }
  validates :state, presence: true, length: { minimum: 2, maximum: 12 }
  validates :phone_number, presence: true, length: { minimum: 10, maximum: 16 }

  # extend FriendlyId
  # belongs_to :guide
  # friendly_id :guide_name, :use => :history
  extend FriendlyId
  belongs_to :guide
  friendly_id :guide_name, use: [:slugged, :history]

  def should_generate_new_friendly_id?
    guide_name_changed?
  end



  def self.search(search)
    where("guide_name LIKE ?", "%#{search}%")
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable, :registerable

  belongs_to :role
  before_create :set_default_role
  # or
  # before_validation :set_default_role

  private
  def set_default_role
    self.role ||= Role.find_by_name('registered')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController

  def guides
    if params[:search]
      @guides = Guide.search(params[:search]).order("guide_name")
    else
      @guides = Guide.all.order("guide_name")
    end
  end

  def create
    @guide = Guide.new guide_params

    unless guide_params.nil?
      @guide.save
    end
  end

  # def new
  #   @guide = Guide.new
  # end

  def edit
    @guide = Guide.find(params[:id])
  end

  def update
    @guide = Guide.find(params[:id])
      @guide.update!(guide_params)
      redirect_to @guide
  end

  def show
    @guide = Guide.find(params[:id])
  end


  private
    def guide_params
      params.require(:guide).permit(:guide_name, :address, :city, :state, :phone_number, :guide_descripion, :latitude, :longitude)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
  end
  
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/views/guides/_form.html.erb
<%= form_for @guide do |f| %>
  <%= f.text_field :guide_name %>
  <%= f.text_field :address %>
  <%= f.text_field :city %>
  <%= f.text_field :state %>
  <%= f.text_field :phone_number %>
  <%= f.text_area  :guide_description %>
  <%= f.button %>
<% end %>

app/views/guides/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h5>Edit this guide's information</h5>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/guides/guides.html.erb
<div class="container-fluid m-t-3">
  <div class="row">
    <div class="col-sm-12 col-lg-6"><!--Start of Left Hand Column-->
      <div id="map">
      </div>
    </div><!--End of Left Hand Column-->
    <div class="col-sm-12 col-lg-6"><!--Start of Right Hand Column-->
      <div class="form-group"><!--Guide Search Function-->
        <%= form_tag(guides_path, :class=>"form-inline guide-search-form pull-lg-right m-b-2", :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Search Guides", :class=>"form-control" %>
            <%= submit_tag "Search", :class=>"btn btn-primary", :name => nil %>
        <% end %>
      </div>

      <% if @guides.present? %>
        <% for guide in @guides do %>
        <div class="col-sm-12 col-md-12 col-lg-12">
          <div class="card card-block">
            <h2 class="card-title"><%= link_to guide.guide_name, guide %></h2>
            <p class="lead m-b-0"><%= guide.address %></p>
            <p class="m-b-0"><%= guide.city %>, <%= guide.state %></p>
            <a href=""><%= guide.phone_number %></a>
            <% if current_user.role_id == 4 %>
            <div id="admin-options" class="pull-lg-right">
              <a class="card-link" href=""><%= link_to "Edit", edit_guide_path(guide) %> | </a>
              <a class="card-link" href=""><%= link_to "Delete", guide_path(guide), method: :delete, data: { confirm: "Are you sure?" }%></a>
            </div>
            <% end %>
          </div>
        </div>
        <% end %>
      <% elsif @guides.empty? %>
        <h2>Looks like we didn't find any results with '<%= params[:search] %>'. Try again!</h2>
      <% else %>
        <%= Guide.find_each do |guide| %>
          <div>
            <h1><%= guide.guide_name %></h1>
            <h3><%= guide.address %></h3>
            <h3><%= guide.city %>, <%= guide.state %></h3>
            <h3><%= guide.phone_number %></h3>
            <%= link_to "Edit", edit_guide_path(guide) %>
          </div>
        <% end %>
      <% end %>
    </div><!--End Of Right Hand Column-->
  </div><!--End Row-->
</div><!--End Container-->

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS'] %>&callback=initMap" async defer></script>

<%= javascript_tag do %>

    function initMap() {
      geocoder = new google.maps.Geocoder();

      var map = new google.maps.Map(document.getElementById('map'), {
        center: {lat: 45.5903359, lng: -120.402882},
        zoom: 7
      });

      <%= Guide.find_each do |guide| %>
        var name = "<%= raw guide.guide_name %>";
        var latitude = <%= guide.latitude %>;
        var longitude = <%= guide.longitude %>;

        var marker = new google.maps.Marker({
            map: map,
            position: {lat: latitude, lng: longitude},
            title: name
        });
      <% end %>

    }

<% end %>

app/views/guides/show.html.erb
<div class="jumbotron">
	<div class="container">
		<div class="row">
			<div class="col-sm-12">
				<h1 class="display-3"><%= @guide.guide_name %></h1>
				<p class="m-b-0 location-category lead"><%= @guide.city %> <%= @guide.state %></p>
			</div>
		</div>
	</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-lg-6">
			<p class="lead"><%= @guide.guide_description %>
				Since 1998 - helping families, business groups, individuals fish with best fishing guides, charter boats, outfitters charter boat operators Oregon Washington. Quality Oregon fishing Charters, Fishing guides Portland Oregon, drift boat fish trips, Columbia River fishing white water rafting trips, party boat, scenic cruise on an Oregon river, ocean salmon charter. Fishing Trip Gift Certificates Oregon fishing guides Portland Oregon fishing charters.</p>
		</div>
		<div class="col-sm-6 col-lg-6">
			<div class="card card-block">
				<h4>Contact Information</h4>
				<p class="lead m-b-0"><%= @guide.address %></p>
				<p><%= @guide.phone_number %></p>
			</div>
		</div>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-primary">
  <%= link_to "FGD", root_path, class: "navbar-brand" %>
  <div class="pull-xs-right">
    <%= link_to "About", about_path, class: "navbar-brand" %>
    <%= link_to "Guides", guides_path, class: "navbar-brand" %>
    <%= link_to "Contact", contact_path, class: "navbar-brand" %>
    <%= render 'devise/menu/registration_items' %>
    <%= render 'devise/menu/login_items' %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fgd</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>
  <%= yield %>
</body>
</html>

app/views/static_pages/about.html.erb
<h1>About page goes here</h1>

app/views/static_pages/contact.html.erb
<h1>Contact page goes here</h1>

app/views/static_pages/home.html.erb
<h1>Homepage goes here</h1>